### ISSUE TITLE
Uses The Complete Wrong Numbers?

### ISSUE THREAD

**Issue by JimLynchCodes** [Tom-Alexander/regression-js#116]
Hi!

This number works for small numbers, but when I pass in numbers that aren't even that big  (in the thousands) the functions seem to use totally different points that are "sorta kinda" close to the points I passed in, but not exactly...

here is some example code: 
```
const regression = require('regression');

const fbPoints = [
  [8, 25_275],	
  [7, 18_485],	
  [6, 22_112],
  [5, 15_934],
  [4, 10_217],
  [3, 3_688],
  [2, 2_940],
  [1, 1_500]
]

console.log('points are: ', fbPoints)

const regLin = regression.linear([...fbPoints])
const regExp = regression.exponential([...fbPoints])

console.log('linear: ', regLin)
console.log('exponential: ', regExp)
```

Here is the output I'm seeing:
```
points are:  [
  [ 8, 25275 ],
  [ 7, 18485 ],
  [ 6, 22112 ],
  [ 5, 15934 ],
  [ 4, 10217 ],
  [ 3, 3688 ],
  [ 2, 2940 ],
  [ 1, 1500 ]
]
linear:  {
  points: [
    [ 8, 25233.01 ],
    [ 7, 21600.4 ],
    [ 6, 17967.79 ],
    [ 5, 14335.18 ],
    [ 4, 10702.57 ],
    [ 3, 7069.96 ],
    [ 2, 3437.35 ],
    [ 1, -195.26 ]
  ],
  predict: [Function: predict],
  equation: [ 3632.61, -3827.87 ],
  r2: 0.93,
  string: 'y = 3632.61x + -3827.87'
}
exponential:  {
  points: [
    [ 8, 29378.09 ],
    [ 7, 21763.82 ],
    [ 6, 16123.04 ],
    [ 5, 11944.24 ],
    [ 4, 8848.51 ],
    [ 3, 6555.14 ],
    [ 2, 4856.17 ],
    [ 1, 3597.54 ]
  ],
  predict: [Function: predict],
  equation: [ 2665.12, 0.3 ],
  string: 'y = 2665.12e^(0.3x)',
  r2: 0.84
}
```

^ You can see that the array contains the correct numbers, but the regression is run of different ones...

You can also try it out here: https://repl.it/@JimLynch/FB-profit-curve-best-fit

So, I am wondering if anyone knows why this is happening, if there is some extra config settings I need to use, why they are not triggered by default, and how I can run regressions with the proper numbers!!

Thanks!!  ♥️

**Comment by ryan-harrington** [comment]
I was confused at first for the same reason. The output points are based on a prediction created with the regression equation. For example:

| Input | Equation | y-value (Predicted) | y-value (Actual) |
| --- | --- | --- | --- |
| 1 | y = 3632.61(1) + -3827.87 | -195.26 | 1500 |
| 2 | y = 3632.61(2) + -3827.87 | 3437.35 | 2940 |
| 3 | y = 3632.61(3) + -3827.87 | 7069.96 | 3688 |

**Comment by JimLynchCodes** [comment]
ahh, I see. Thanks @LeSirh!

So you pass in an array of points, and the "points" returned are the same x values that you passed in but with the y values on the equation line? Is that right?

**Comment by ryan-harrington** [comment]
> ahh, I see. Thanks @LeSirH!
> 
> So you pass in an array of points, and the "points" returned are the same x values that you passed in but with the y values on the equation line? Is that right?

Yep!
