### ISSUE TITLE
yn=0 creates error in polynomial regression

### ISSUE THREAD

**Issue by dph777** [Tom-Alexander/regression-js#13]
Using data set [-18, -13], [1, 0], [6,-31],[28, 14] to do polynomial degree 3 regression yields y = 0x^3 + 0.04x^2 + -0.63x + -28.89 . The problem seems to stem from y1 = 0 because if it is changed to a non-0 value, such as 2, a correct regression equation results: y = 0.01x^3 + -0.16x^2 + -6.08x + 8.23. Similar erratic behavior seems to occur whenever any y value is 0.

**Comment by Tom-Alexander** [comment]
I cannot reproduce this, I have added tests to check it in #59.
