### ISSUE TITLE
Additional regressions

### ISSUE THREAD

**Issue by 153957** [Tom-Alexander/regression-js#20]
The HiSPARC project uses a derived version of this script in an analysis tool for students to work with cosmic-ray data. We were very pleased to have found this script, it saved us a lot of time. We did miss some functions so we extended the number of regression methods to include a sine and gaussian fit and added an exponential regression where each point has equal weight. Perhaps you can add these regressions back into your script, we did modify some of the code style and such, but the essentials should be easy to copy. You can find these added regressions (with references) in our latest version of the script:

https://github.com/HiSPARC/jsparc/blob/master/scripts/regression.js

Feel free to use it..

**Comment by yangchenyun** [comment]
:+1: for the added regression model and the mathjax conversion. 

May be could making a PR to make the merge easier for Tom-Alexander@?

**Comment by 153957** [comment]
I currently do not have time to do that. Perhaps later, or someone else will need to do it.
