### ISSUE TITLE
exponential decay

### ISSUE THREAD

**Issue by cerenaltunal** [Tom-Alexander/regression-js#21]
Hi,
Exponential function works for exponential growth but not exponential decay. Do you have any suggestions how to fix it?

Bests

**Comment by aghasemi** [comment]
I've had the same problem (in MATLAB though). 

If {(x,y)} is your original data with exponential decay, then {(x,1/y)} will have exponential "growth". So you can fit and exponential function to {(x,1/y)} leading to a function, say f(x)=a*exp(b*x) and then use g(x)=1/f(x) as the regressor for your original data.
