### ISSUE TITLE
Feature Request - Model comparison

### ISSUE THREAD

**Issue by meeple142** [Tom-Alexander/regression-js#24]
Hello,
Thank you for this great library. It would be great if when you took a regression that on the obj that was returned it would have some value telling you how well the regression fits the supplied data. I think r squared could work but I have also heard of arguments for s or s squared. its called Standard Error of the Regression, has other names too see [Why is there no r squared for nonlinear regression](http://blog.minitab.com/blog/adventures-in-statistics/why-is-there-no-r-squared-for-nonlinear-regression). You most likely know more about which would be more helpful or which would be better to use when and maybe you know a better tool to compare the fit of the regression. Also, maybe there is already a way to get the comparison easy with your lib and i just don't know. 

I would like this feature because the data I have has holes in it and they have different structures. It is not crucial to be very exact for my task, but for example, its clear that in certain cases an exponential fix would be better than a linear fit. But there is tons of data so it would be nice to programmatically try different fitting models and then compare R or S and then decide on the best fit. I know that it would not be a good way for research but like is said its not crucial I just need my holes filled and this would allow me to be just a little more accurate than always using linear.

Like I said thank you again!

**Comment by Tom-Alexander** [comment]
I have decided this is outside the scope of the module
