### ISSUE TITLE
Confidence interval

### ISSUE THREAD

**Issue by nite** [Tom-Alexander/regression-js#27]
How hard would it be to patch regression.js to give us a confidence interval as well?

**Comment by Tom-Alexander** [comment]
Hi @nite, 
Like a confidence interval for the gradient? I don't think calculating that would be too difficult, but it's probably outside the scope of this library. I do intend on adding the coefficient of determination (and most likely the standard error) in the near future.

``` 
var model = regression('linear', data);
var standardError = model.standardError;
var stat = model.equation[0]; // gradient
var confidenceLevel = 0.95;
var DF = data.length - 2;
var criticalProbability = 1 - confidenceLevel;
var criticalValue =  tDistribution(DF, criticalProb);
var marginOfError = criticalValue * standardError;
var confidenceInterval = [stat - marginOfError, stat + marginOfError];
```

**Comment by nite** [comment]
Yes, we're replicating something like this from ggplot in d3
http://stats.stackexchange.com/questions/85560/shape-of-confidence-interval-for-predicted-values-in-linear-regression

Here's my implementation:

**usage:**
```
import regressionService from '/services/regressionService';
regress = regression('linear', inputPoints, 3);
_.merge(regress, regressionService.getErrorLines(inputPoints, regress.points));
```

**regressionService.js:**
```
import math from 'mathjs';
import _ from 'lodash';

function RegressionService(){
    function getErrorMargin(inputPoints, outputPoints) {
        var standardErrorSquared = _.sum(
                _.zip(inputPoints.map(x => x[1]), outputPoints.map(x => x[1]))
                    .map(pair => Math.pow(pair[1] - pair[0], 2)))
            / (inputPoints.length - 2);

        var inputMatrix = inputPoints.map(p => [1, p[0]]);

        return math.sqrt(
            math.diag(
                math.multiply(
                    math.multiply(
                        math.multiply(inputMatrix, standardErrorSquared),
                        math.inv(math.multiply(math.transpose(inputMatrix), inputMatrix))),
                    math.transpose(inputMatrix))));
    }

    function getErrorLines(inputPoints, outputPoints) {
        var errorMargin = getErrorMargin(inputPoints, outputPoints);
        var inputXs = inputPoints.map(x => x[0]);
        var outputYs = outputPoints.map(p => p[1]);
        var lowerErrorYs = math.subtract(outputYs, errorMargin);
        var upperErrorYs = math.add(outputYs, errorMargin);
        return {
            lowerErrorPoints: _.zip(inputXs, lowerErrorYs),
            upperErrorPoints:  _.zip(inputXs, upperErrorYs)
        }
    }

    return {
        getErrorLines: getErrorLines
    }
}

export default new RegressionService();
```

**Comment by mikelang919** [comment]
@Tom-Alexander - What is your ETA on adding coefficient of determination (r2)? This is the only feature keeping us from using this library right now.

**Comment by Tom-Alexander** [comment]
I plan on merging it this week @mikelang919

**Comment by ptsurko** [comment]
Hi @Tom-Alexander, @nite,

I need to create d3 plot with confidence intervals for linear regression similar to https://web.stanford.edu/~mwaskom/software/seaborn/examples/regression_marginals.html and I am trying to use your RegressionService to get upper and lower lines 

Is it enough to just call getErrorLines and used returned data to draw lines?
Do you know the formulas used in calculation?

I can't find good docs and formulas to calculate those lines

Thanks,
Pavel

**Comment by bgits** [comment]
I see this library added r2 are there plans for standard error as well?
