### ISSUE TITLE
Question on usage for trends

### ISSUE THREAD

**Issue by maeishoj** [Tom-Alexander/regression-js#31]
Hello and thanks for this useful library!

I am new to this and I was wondering if someone could land an hand..
I am trying to find a way to forecast future values given a dataset.

This is what i am doing: 

(PS: import the following:
<script data-require="sugar@*" data-semver="1.3.8" src="//cdnjs.cloudflare.com/ajax/libs/sugar/1.3.8/sugar.min.js"></script>
    <script data-require="sugar@*" data-semver="1.3.8" src="//cdnjs.cloudflare.com/ajax/libs/sugar/1.3.8/sugar.full.min.js"></script>
    <script data-require="sugar@*" data-semver="1.3.8" src="//cdnjs.cloudflare.com/ajax/libs/sugar/1.3.8/sugar.full.dev.js"></script>
)
var data = [];
        var initialDate = new Date().addDays(-40).getTime();
        var initialLevel = 100;
        var currentDate = initialDate;
        var tmp = [];

        for(var i = 0; i<=40; i++){
            currentDate = new Date(initialDate).addDays(i).getTime();
            tmp = [currentDate, (initialLevel-i)];
            data.push(tmp);
        }

        var result = regression('linear', data);
        console.log(result);
        
 Basically I am having a number "InitialLevel" starting from 100 and decrease linearly until 60. The day starting at today - 40 days and adding one day in each loop. So the last item in point array in result becomes today's date and level of ~60.  However if I want to know what the level is expected to be tomorrow, I thought I would just do:

tmp = [new Date(initialDate).addDays(41).getTime(), null];
        data.push(tmp);
        result = regression('linear', data);
        
        console.log(result);

So that I would add another point in the array with tomorrow's date, and putting null as value to get the trend as I read in the front page.

However the last item in the points array in results is now 80, and all the previous values are also changed, so I believe I am missing the point on how to use this.

I tried to make a plunkr but I couldn't get regression to work. 

I would appreciate if anyone could lead me on the right track in terms of what I actually need to do..

**Comment by Tom-Alexander** [comment]
The regression result will contain an equation that models your data. You can apply this to the next date:

```
var nextDate = new Date(initialDate).addDays(41).getTime();
var result = regression('linear', data);
var nextLevel = result.equation[0] * nextDate + result.equation[1];
```

**Comment by maeishoj** [comment]
Great! This is exactly what i needed! Thank you so much!
