### ISSUE TITLE
Repo example/index.html points to non-responding server

### ISSUE THREAD

**Issue by amergin** [Tom-Alexander/regression-js#36]
The example tries to fetch `jquery.flot.js` from `http://tomalexander.co.nz/regression-js/jquery.flot.js` which is not responding. Consider using a proper CDN instead: `https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.js`.

**Comment by Tom-Alexander** [comment]
Fixed!
