### ISSUE TITLE
Add rsquare to polynomial regression

### ISSUE THREAD

**Issue by tsghosh** [Tom-Alexander/regression-js#37]
Can you add r2 in as an attribute.

> > polynomial regression Regression.js
> > Line 216: return {equation: equation, points: results, string: string};

**Comment by ahalota** [comment]
This has been solved and pull request submitted: https://github.com/Tom-Alexander/regression-js/pull/28 Until it is accepted, you can just copy the code from there, it looks correct as far as I can tell.

**Comment by Tom-Alexander** [comment]
Added in #59
