### ISSUE TITLE
ReferenceError on regression function call

### ISSUE THREAD

**Issue by harishnavnit** [Tom-Alexander/regression-js#38]
Hi, 

I'm unable to figure out how exactly to put this to use. I'm working on a [project](https://github.com/harishnavnit/noc) that's requiring me to make predictions on the next set of values, given an input of a set of values(latitude, longitude coordinates in this case).

I've installed `regression` package from node repositories using `npm install --save regression`, which duly shows up in my `package.json` file as `"regression": "^1.2.1"`. 
I call it in my top level node server management file as such(`app.js`)

```
var regression = require('regression');
```

and include it in on the html side as follows, 

```
<script src="/regression/src/regression.js"></script>
<script src="js/path.js"></script>
```

and finally I call it in `path.js` file as follows

```
function processMarkers(actualData) {
    var fakeData = [ [0,1],[32, 67], [12, 79] ];
    var result = regression('linear', fakeData);
    console.log("Result = " + result);
}
```

Am I missing something here ? I get a `ReferenceError` stating 

```
ReferenceError: regression is not defined
```

**Comment by ZeepXanflorp** [comment]
I also get this - I'm pretty sure it's because I'm new to the sourcing, and I don't understand the declaration. I'm using the minified version in a script tag. I've opened your example in a browser and it works, but when I move it to an electron app it fails. The minified code is available in the Chrome dev tools.

**Comment by Tom-Alexander** [comment]
`regression` is bound to the window when no module loader is present. You will need to ensure that the script has been loaded before you access it if one is not available. The documentation will be updated to make this more apparent.
