### ISSUE TITLE
Other regression models (feature request)

### ISSUE THREAD

**Issue by kreynaldo** [Tom-Alexander/regression-js#41]
. Semi-logarithmic: f(x) = ln (a + bx)
. Growth                  f(x) = e^(a + bx)
. Compound            f(x) = a b^x
. Hyperbolic             f(x) = a + b/x
. S curve                  f(x) = e^(a + b/x)
. Logistic:                 f(x) = 1 / (a + b c^x)

**Comment by kreynaldo** [comment]
I was able to include the Growth method: y = e^(a + bx), using the following piece of code:

...
```
            growth: function(data) {
                
                var data1 = data.slice(0);
                // transform values using: y = e ^ (ax + b) =>  ln y = ax + b
                for(var d in data1) data1[d][1] = Math.log(data1[d][1]);

                var result = regression("linear",data1);

                for(var p in result.points) result.points[p][1] = Math.pow(Math.E,result.points[p][1]);
                result.string = 'y = e ^ (' + Math.round(result.equation[0]*10000) / 10000 + 'x + '+Math.round(result.equation[1]*10000) / 10000+')';

                return result;
            },
```
...
the key was transform original data, so you get a simple linear regression.

Semilogarithmic didn't work beacuse the transformation wasn't feasible to compute.

**Comment by gilles-yvetot** [comment]
@kreynaldo what do you mean by:

> Semilogarithmic didn't work beacuse the transformation wasn't feasible to compute.

Did you try to compute the partial derivatives ?

**Comment by kreynaldo** [comment]
@gilles-yvetot I'm pretty sure I didn't try to compute the partial derivatives...

**Comment by gilles-yvetot** [comment]
I tried but it does not lead to something linear. I might try to linearize the data to fall back to a ax+b model
