### ISSUE TITLE
Clarification: Regression with Seasonality and Exponential Smoothing

### ISSUE THREAD

**Issue by NilsFrkal** [Tom-Alexander/regression-js#45]
Hi experts,

Does any of the regression functions support seasonality and/or exponential smoothing? Could this be added? If not, is anyone aware of a javascript library which support this already?

Thank you very much.

Best, Nils

**Comment by Tom-Alexander** [comment]
Hi @NilsFrkal, supporting multiple linear regression (required for seasonal data), shouldn't be 
too difficult to implement in this library, and is probably a common use case. I will investigate adding this feature.

Exponential smoothing probably isn't something that I would addd to this library, but would likely be trivial to implement yourself. Perhaps something similar to:

```javascript
smoothed = [data[0]];
var alpha = 0.1; // number between 0 and 1

for (var i = 1; i < data.length; i++) {
  var y = alpha * data[i][0] + (1 - alpha) * smoothed[i - 1];
  smoothed.push([data[i][0], y]);
}
```

**Comment by NilsFrkal** [comment]
Thanks a lot for your fast response. It would be great if this could be added and also thanks for the smoothing part. All the best, Nils
