### ISSUE TITLE
Seeing if interested in PR

### ISSUE THREAD

**Issue by ChaseLewis** [Tom-Alexander/regression-js#51]
I added BIC model comparison to regression.js with an 'auto' model selection that can be passed different model options and will select the best based on the BIC criteria and added a 'predict' function to each returned object so you can invoke the regression in a uniform f(x) style fashion.

https://github.com/ChaseLewis/regression-js
Not sure if this functionality would be appreciated in the main branch or not.

**Comment by Tom-Alexander** [comment]
Thanks for the suggestion, but I think this is outside of the scope of this module.
