### ISSUE TITLE
Polynomial regression example on github.io is incorrect

### ISSUE THREAD

**Issue by teldridge11** [Tom-Alexander/regression-js#54]
The example on the github.io page shows the following example code for polynomial regression:

```
var data = [[0,1],[32, 67] .... [12, 79]]
var result = regression('polynomial', 4)
```

The call to `regression` here does not include the `data` variable.

In the github documentation example, the `data` var is correctly included in the `regression` call:

```
var data = [[0,1],[32, 67] .... [12, 79]];
var result = regression('polynomial', data, 4);
```

**Comment by Tom-Alexander** [comment]
Fix in #64
