### ISSUE TITLE
slop is showing as NaN if data contains negative values

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [Tom-Alexander/regression-js#56]
Hi I have an array of data like the following but the slop is showing as NaN

`[ 1497870825385, '0.000002' ],
  [ 1497870825385, '-0.000007' ],
  [ 1497870829744, '0.000026' ],
  [ 1497870834265, '-0.000043' ],
  [ 1497870834266, '-0.000029' ],
  [ 1497870834266, '-0.000021' ],
  [ 1497870838505, '-0.000023' ],
  [ 1497870842728, '-0.000023' ],
  [ 1497870842728, '-0.000024' ],
  [ 1497870842728, '-0.000037' ],
  [ 1497870846866, '-0.000039' ],
  [ 1497870851267, '-0.000026' ],
  [ 1497870855751, '-0.000043' ],
  [ 1497870855751, '-0.000062' ],
  [ 1497870855751, '-0.000039' ],
  [ 1497870855752, '-0.000011' ],
  [ 1497870859925, '0.000020' ]`

I am using simple regression, what could be wrong here?

**Comment by Tom-Alexander** [comment]
The input must a number, you are using strings. Try `[[ 1497870825385, 0.000002 ]...]` instead of `[[1497870825385, '0.000002']...]`
