### ISSUE TITLE
Formatting the equation string output? e.g. number of digits, after decimal, etc.

### ISSUE THREAD

**Issue by daluu** [Tom-Alexander/regression-js#60]
For equations (linear and/or polynomial regression) where the x value is very small, e.g. `y = 0.0002x + 5.26`, is there a way to format the string representation of the equation? It seems to default to 1 digit, e.g. `y = 0x + 5.26`.

I was comparing this library's output with Excel trendline analysis. Excel by default also rounds the x slope value (0x) but one can edit the formatting to show more digits so you get a more realistic slope. How to adjust that here? It would be nice if it was adjustable so the user doesn't have to dig into the code of this library to muck with the formatting/conversion of equation to string.

**Comment by daluu** [comment]
Sample data for this:

`var data = [[12000,7],[14000,8],[18000,8],[21000,9],[24000,9],[28000,10]];`

**Comment by daluu** [comment]
Well, I overlooked that I can pull the values/coefficients off the equation field and reassemble into my own string, but would be nice if this was nicely wrapped so one wouldn't have to muck around.

**Comment by Tom-Alexander** [comment]
Rounding can be configured with the `precision` option. Documentation for this feature is added in #59
