### ISSUE TITLE
How to use this library with node.js (server) side?

### ISSUE THREAD

**Issue by daluu** [Tom-Alexander/regression-js#61]
For case of not using in browser, other than copy and pasting the code into one's main codebase or modifying the library to export its functions, is there any way the current library can be imported for use in node.js CLI/script or server side  code? e.g.

```
regression = require('regression-js'); 
//or regression = require('./pathTo/regression.min.js');
var data = [[0,1],[32, 67] .... [12, 79]];
var result = regression('linear', data);
```

**Comment by Tom-Alexander** [comment]
This module works on node. It can be installed with [npm](https://npmjs.com/package/regression):
```
npm install --save regression
```

**Comment by daluu** [comment]
But how to import it and call the library from node.js (not in browser)? The readme doesn't show that.

It fails to find "regression" module. On browser side, it's just an easy include of the script via script tag.

You don't mention how to use it in the README on server side. Please clarify.
