### ISSUE TITLE
Unexpectef

### ISSUE THREAD

**Issue by guru-DeV-002** [Tom-Alexander/regression-js#71]

**Comment by guru-DeV-002** [comment]
<img width="1051" alt="screen shot 2017-09-09 at 3 57 19 pm" src="https://user-images.githubusercontent.com/21274326/30239321-a4e46980-9577-11e7-9f9d-ba185124cb98.png">

tried to fix this using Math.pow();

**Comment by Tom-Alexander** [comment]
There was an issue with the build system which has now been fixed in 2.0.1
