### ISSUE TITLE
How to use “regression-js” in angular 2 project

### ISSUE THREAD

**Issue by NimishMrPerfect** [Tom-Alexander/regression-js#74]
I am importing the Regression npm module [https://www.npmjs.com/package/regression][1] within my Angular 2 application to use the Linear Regression function. I have install package using `"npm install regression"` . Now I have tried few things to use that package : 

**First thing which i have tried:**

    import regression from 'regression';
    const result= regression.linear([0, 1], [32, 67], [12, 79]); // this line is giving error, -- can not use linear on undefined.

**Second thing which I have tried:**

    import {Regression} from "regression";
    regresiionvar: Regression;
    const result=  this.regresiionvar.linear([0, 1], [32, 67], [12, 79]); // but still undefined error.

 **third thing which I have tried:**

    import {Regression} from "regression";
    regresiionvar: Regression = new Regression().init({});
    const result=  this.regresiionvar.linear([0, 1], [32, 67], [12, 79]);//  but still the same undefined error.

I do not know, which thing I am missing, this is quite popular package(look at the number of downloads daily.) 

Can any one please share the working example of [regression-js][1] with angular 2.

I found one similar question for this, [https://stackoverflow.com/questions/41556317/import-non-core-npm-library-into-angular-2-app#comment81532045_41556317][2] , but it also do not have any correct solution. 

Any help will be appreciated.

  [1]: https://www.npmjs.com/package/regression
  [2]: https://stackoverflow.com/questions/41556317/import-non-core-npm-library-into-angular-2-app#comment81532045_41556317

**Comment by Tom-Alexander** [comment]
This should be sufficient. Perhaps you are using an older version?

```
import regression from 'regression';
const result = regression.linear([[0, 1], [32, 67], [12, 79]);
```
