### ISSUE TITLE
Example not working 

### ISSUE THREAD

**Issue by dean-vollebregt** [Tom-Alexander/regression-js#76]
After installation via :
npm install regression --save
 
Then running the example script using node

const regression = require("regression");
let result = regression.linear([0, 1], [32, 67], [12, 79]);
let gradient = result.equation[0];
let yIntercept = result.equation[1];

The results are:

console.log(gradient);  --> NaN
console.log(yIntercept); --> NaN

**Comment by gedeagas** [comment]
yep got the same result

**Comment by Tom-Alexander** [comment]
I think you are missing brackets around the coordinates:

```
const regression = require("regression");
let result = regression.linear([[0, 1], [32, 67], [12, 79]]);
let gradient = result.equation[0];
let yIntercept = result.equation[1];
```
