### ISSUE TITLE
X intercept?

### ISSUE THREAD

**Issue by Tzikas** [Tom-Alexander/regression-js#78]
How do I predict the x intercept of a polynomial or exponential function?  

I have data with Date.now() and percentage values like so ```[[1515569440034,1],[1515569456654,0.8333333333333334],[1515569522244,0.16666666666666666],[1515569563911,0.16666666666666666],[1515569594707,0.16666666666666666],[1515569628485,0.16666666666666666],[1515569637613,0.6666666666666666],[1515569657209,0.16666666666666666],[1515569745083,0.16666666666666666]]``` and I'm trying to find the Date when the percentage will equal zero.  The prediction function seems to return the y value but I'm looking for the x.  Am I missing something obvious?   

Also do I need to normalize the numbers because one is so large and the other is so small?

**Comment by Tom-Alexander** [comment]
You could use the model coefficients to solve for `y = 0`. Depending on your data set, the [bisection method](https://en.wikipedia.org/wiki/Bisection_method) may be appropriate. https://en.wikipedia.org/wiki/Root-finding_algorithm
