### ISSUE TITLE
Save the regression model as JSON

### ISSUE THREAD

**Issue by Seikon** [Tom-Alexander/regression-js#90]
hi!

I would like to know if there is a way, once the reggresion model has filled, to save it in a persitence way (JSON format for example), out of runtime enviroment in order to use and "share knowledge" beetwen systems.

**Comment by Seikon** [comment]
@Tom-Alexander  if not, I would like to contribute this libray for make it possible :)

**Comment by Tom-Alexander** [comment]
Just stringify the result:

```javascript
import regression from 'regression';
const result = regression.linear([[0, 1], [32, 67], [12, 79]]);
JSON.stringify(result);
```
